// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:

//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.

// What is the value of the first triangle number to have over five hundred divisors?

function triangle_sum(num) {
    var sum = 0;
    for(var i=1; i<=num; i++) {
      sum += i;
    }
    return sum;
  }
  
  function num_divisors(num) {
    var divisors = [];
    var max = num - 1;
    divisors.push(1);
    divisors.push(num);
      
    for(var i=2; i<max; i++) {
      if(num % i == 0) {
        divisors.push(i);
        divisors.push(num / i);
        max = num / i;
      }
    }
    return divisors.length;
  }
  
  function triangle_num_over_x_divisors(min_divisors) {
    var num, tri_sum, divisors = 0;
      
    for(num = 1; divisors < min_divisors; num++) {
      tri_sum = triangle_sum(num);
      divisors = num_divisors(tri_sum);
    }
    return tri_sum;
  }
  
  console.log(triangle_num_over_x_divisors(500));
  //solution
//   76576500